name: Deploy_test

on: [ push ]

jobs:
  build:
    name: Deploy app and perform tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: isbang/compose-action@v1.4.1
        with:
          compose-file: docker-compose.yml
      - name: Set up Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - name: Install project dependencies
        run: pip install --no-cache-dir -r tests/requirements.txt
      - name: Run tests
        run: |
          pytest tests